# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_film.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(407, 534)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 381, 491))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.title_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.title_input.setObjectName("title_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.title_input)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.description_input = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.description_input.setObjectName("description_input")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.description_input)
        self.year_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.year_input.setObjectName("year_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.year_input)
        self.genre_input = QtWidgets.QComboBox(self.formLayoutWidget)
        self.genre_input.setObjectName("genre_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.genre_input)
        self.age_limit_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.age_limit_input.setObjectName("age_limit_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.age_limit_input)
        self.time_input = QtWidgets.QTimeEdit(self.formLayoutWidget)
        self.time_input.setObjectName("time_input")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.time_input)
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setGeometry(QtCore.QRect(0, 510, 100, 25))
        self.save_button.setText('Сохранить')
        self.error_label = QtWidgets.QLabel(Form)
        self.error_label.setGeometry(QtCore.QRect(120, 510, 280, 20))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Название"))
        self.label_2.setText(_translate("Form", "Год выпуска"))
        self.label_3.setText(_translate("Form", "Жанр"))
        self.label_4.setText(_translate("Form", "Возрастное ограничение"))
        self.label_5.setText(_translate("Form", "Продолжительность"))
        self.label_6.setText(_translate("Form", "Описание"))
