# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_theater_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 250)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label.setObjectName("label")
        self.name_input = QtWidgets.QLineEdit(Form)
        self.name_input.setGeometry(QtCore.QRect(70, 20, 171, 20))
        self.name_input.setText("")
        self.name_input.setObjectName("name_input")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 51, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 51, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 51, 21))
        self.label_4.setObjectName("label_4")
        self.country_box = QtWidgets.QComboBox(Form)
        self.country_box.setGeometry(QtCore.QRect(70, 60, 171, 22))
        self.country_box.setObjectName("country_box")
        self.city_box = QtWidgets.QComboBox(Form)
        self.city_box.setGeometry(QtCore.QRect(70, 100, 171, 22))
        self.city_box.setObjectName("city_box")
        self.street_box = QtWidgets.QComboBox(Form)
        self.street_box.setGeometry(QtCore.QRect(70, 140, 171, 22))
        self.street_box.setObjectName("street_box")
        self.building_input = QtWidgets.QLineEdit(Form)
        self.building_input.setGeometry(QtCore.QRect(70, 180, 171, 20))
        self.building_input.setText("")
        self.building_input.setObjectName("building_input")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 51, 21))
        self.label_5.setObjectName("label_5")
        self.country_input = QtWidgets.QLineEdit(Form)
        self.country_input.setEnabled(True)
        self.country_input.setGeometry(QtCore.QRect(260, 60, 171, 20))
        self.country_input.setText("")
        self.country_input.setObjectName("country_input")
        self.city_input = QtWidgets.QLineEdit(Form)
        self.city_input.setEnabled(True)
        self.city_input.setGeometry(QtCore.QRect(260, 100, 171, 20))
        self.city_input.setText("")
        self.city_input.setObjectName("city_input")
        self.street_input = QtWidgets.QLineEdit(Form)
        self.street_input.setEnabled(True)
        self.street_input.setGeometry(QtCore.QRect(260, 140, 171, 20))
        self.street_input.setText("")
        self.street_input.setObjectName("street_input")
        self.commit_button = QtWidgets.QPushButton(Form)
        self.commit_button.setGeometry(QtCore.QRect(10, 220, 75, 23))
        self.commit_button.setText('Сохранить')
        self.error_label = QtWidgets.QLabel(Form)
        self.error_label.setGeometry(QtCore.QRect(100, 220, 300, 25))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Название:"))
        self.label_2.setText(_translate("Form", "Страна:"))
        self.label_3.setText(_translate("Form", "Город:"))
        self.label_4.setText(_translate("Form", "Улица:"))
        self.label_5.setText(_translate("Form", "Здание:"))
