# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'session_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 610)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 560, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 530, 131, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 131, 16))
        self.label_6.setObjectName("label_6")
        self.purchase_button = QtWidgets.QPushButton(Form)
        self.purchase_button.setGeometry(QtCore.QRect(384, 580, 111, 23))
        self.purchase_button.setObjectName("purchase_button")
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setGeometry(QtCore.QRect(190, 20, 301, 16))
        self.name_label.setText("")
        self.name_label.setObjectName("name_label")
        self.genre_label = QtWidgets.QLabel(Form)
        self.genre_label.setGeometry(QtCore.QRect(190, 50, 301, 16))
        self.genre_label.setText("")
        self.genre_label.setObjectName("genre_label")
        self.age_limit_label = QtWidgets.QLabel(Form)
        self.age_limit_label.setGeometry(QtCore.QRect(190, 80, 301, 16))
        self.age_limit_label.setText("")
        self.age_limit_label.setObjectName("age_limit_label")
        self.description_label = QtWidgets.QLabel(Form)
        self.description_label.setGeometry(QtCore.QRect(190, 110, 301, 371))
        self.description_label.setText("")
        self.description_label.setObjectName("description_label")
        self.price_label = QtWidgets.QLabel(Form)
        self.price_label.setGeometry(QtCore.QRect(190, 530, 301, 16))
        self.price_label.setText("")
        self.price_label.setObjectName("price_label")
        self.time_label = QtWidgets.QLabel(Form)
        self.time_label.setGeometry(QtCore.QRect(190, 560, 301, 16))
        self.time_label.setText("")
        self.time_label.setObjectName("time_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Фильм:"))
        self.label_2.setText(_translate("Form", "Время сеанса:"))
        self.label_3.setText(_translate("Form", "Возрастное Ограничение:"))
        self.label_4.setText(_translate("Form", "Цена билета:"))
        self.label_5.setText(_translate("Form", "Жанр:"))
        self.label_6.setText(_translate("Form", "Описание:"))
        self.purchase_button.setText(_translate("Form", "Перейти к покупке"))
