# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'session_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(384, 224)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 47, 21))
        self.label.setObjectName("label")
        self.film_name = QtWidgets.QLineEdit(Form)
        self.film_name.setGeometry(QtCore.QRect(100, 30, 191, 20))
        self.film_name.setReadOnly(True)
        self.film_name.setObjectName("film_name")
        self.film_choose = QtWidgets.QPushButton(Form)
        self.film_choose.setGeometry(QtCore.QRect(300, 30, 75, 23))
        self.film_choose.setObjectName("film_choose")
        self.room_choose = QtWidgets.QPushButton(Form)
        self.room_choose.setGeometry(QtCore.QRect(300, 70, 75, 23))
        self.room_choose.setObjectName("room_choose")
        self.room_name = QtWidgets.QLineEdit(Form)
        self.room_name.setGeometry(QtCore.QRect(100, 70, 191, 20))
        self.room_name.setReadOnly(True)
        self.room_name.setObjectName("room_name")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 47, 21))
        self.label_2.setObjectName("label_2")
        self.price_input = QtWidgets.QLineEdit(Form)
        self.price_input.setGeometry(QtCore.QRect(100, 110, 191, 20))
        self.price_input.setObjectName("price_input")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 71, 21))
        self.label_4.setObjectName("label_4")
        self.time_input = QtWidgets.QDateTimeEdit(Form)
        self.time_input.setGeometry(QtCore.QRect(100, 150, 194, 22))
        self.time_input.setObjectName("time_input")
        self.error_output = QtWidgets.QLabel(Form)
        self.error_output.setGeometry(QtCore.QRect(10, 190, 261, 16))
        self.error_output.setText("")
        self.error_output.setObjectName("error_output")
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setGeometry(QtCore.QRect(300, 190, 75, 23))
        self.save_button.setObjectName("save_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Фильм:"))
        self.film_choose.setText(_translate("Form", "Выбрать"))
        self.room_choose.setText(_translate("Form", "Выбрать"))
        self.label_2.setText(_translate("Form", "Зал:"))
        self.label_3.setText(_translate("Form", "Цена билета:"))
        self.label_4.setText(_translate("Form", "Время сенса:"))
        self.save_button.setText(_translate("Form", "Сохранить"))
